//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZBStatusUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NZBStatusUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon green_down_arrow_hi {
            get {
                object obj = ResourceManager.GetObject("green_down_arrow_hi", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find &apos;apikey&apos; file in application folder.
        /// </summary>
        internal static string MainForm_MainForm_Couldn_t_find__apikey__file_in_application_folder {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Couldn_t_find__apikey__file_in_application_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Api key.
        /// </summary>
        internal static string MainForm_MainForm_No_Api_key {
            get {
                return ResourceManager.GetString("MainForm_MainForm_No_Api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server file.
        /// </summary>
        internal static string MainForm_MainForm_No_server_file {
            get {
                return ResourceManager.GetString("MainForm_MainForm_No_server_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server file couldn&apos;t be found.
        /// </summary>
        internal static string MainForm_MainForm_Server_file_couldn_t_be_found {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Server_file_couldn_t_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string MainForm_RefreshUI_delete {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDLE.
        /// </summary>
        internal static string MainForm_RefreshUI_IDLE {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key has been found.
        /// </summary>
        internal static string MainForm_RefreshUI_No_API_key_has_been_found {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_No_API_key_has_been_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string MainForm_RefreshUI_Pause {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSED.
        /// </summary>
        internal static string MainForm_RefreshUI_PAUSED {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string MainForm_RefreshUI_Resume {
            get {
                return ResourceManager.GetString("MainForm_RefreshUI_Resume", resourceCulture);
            }
        }
    }
}
